# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.portComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.portComboBox.setObjectName("portComboBox")
        self.verticalLayout_2.addWidget(self.portComboBox)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout_2.addWidget(self.connectButton)
        self.rxTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.rxTextEdit.setObjectName("rxTextEdit")
        self.verticalLayout_2.addWidget(self.rxTextEdit)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_2.addWidget(self.clearButton)
        self.commandLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.commandLineEdit.setObjectName("commandLineEdit")
        self.verticalLayout_2.addWidget(self.commandLineEdit)
        self.sendMsgButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendMsgButton.setObjectName("sendMsgButton")
        self.verticalLayout_2.addWidget(self.sendMsgButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSave_File = QtWidgets.QAction(MainWindow)
        self.actionSave_File.setObjectName("actionSave_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClose_File = QtWidgets.QAction(MainWindow)
        self.actionClose_File.setObjectName("actionClose_File")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionAbout_this_software = QtWidgets.QAction(MainWindow)
        self.actionAbout_this_software.setObjectName("actionAbout_this_software")
        self.actionSensor_User_Manual = QtWidgets.QAction(MainWindow)
        self.actionSensor_User_Manual.setObjectName("actionSensor_User_Manual")
        self.actionSensor_Utility_User_Manual = QtWidgets.QAction(MainWindow)
        self.actionSensor_Utility_User_Manual.setObjectName("actionSensor_Utility_User_Manual")
        self.actionEdit_Parameters = QtWidgets.QAction(MainWindow)
        self.actionEdit_Parameters.setObjectName("actionEdit_Parameters")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Communication"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.sendMsgButton.setText(_translate("MainWindow", "Send Message"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionSave_File.setText(_translate("MainWindow", "Save File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionClose_File.setText(_translate("MainWindow", "Close File"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionAbout_this_software.setText(_translate("MainWindow", "About this software"))
        self.actionSensor_User_Manual.setText(_translate("MainWindow", "Sensor User Manual"))
        self.actionSensor_Utility_User_Manual.setText(_translate("MainWindow", "Sensor Utility User Manual"))
        self.actionEdit_Parameters.setText(_translate("MainWindow", "Edit Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
